### ISSUE TITLE
don't mark Noto Arabic Naskh in yellow

### ISSUE THREAD

**Issue by juhp** [fedora-i18n/font-status#3]
I think Noto Arabic Naskh is the correct or corresponding font face for Arabic "Serif"
so it would be nicer not to flag it in yellow color if possible.

**Comment by tagoh** [comment]
The feature to draw a color against test cases in a package repo has been implemented in fontquery 1.19. the status page should be reflected their results now.

The orange text isn't yet determined in test cases. we need to update it.
The red text may be a bug in font packages. that result is explicitly denied in a test case.
