### ISSUE TITLE
RFE update when there a change of fonts

### ISSUE THREAD

**Issue by juhp** [fedora-i18n/font-status#4]
It might be a good feature to update the table whenever one of the fonts packages is updated (ie rebuilt) perhaps.
Well this sounds potentially non-trivial so I am not sure how easy/feasible this is in practice.

Conversely a simpler solution might be to only update the published table when the results change?

**Comment by tagoh** [comment]
The CI pipeline is running daily though, deploying the page happens only when something changed in default fonts.
Though history doesn't record what releases got changed. So all the supported releases bumped at this moment. Is it what you want right?

**Comment by tagoh** [comment]
The history of results has been improved and recorded per releases now.
